#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <webots/gps.h>
#include <webots/gyro.h>
#include <webots/inertial_unit.h>
#include <webots/motor.h>
#include <webots/robot.h>
#include <webots/distance_sensor.h>
#include "pid_controller.h"

#define PI 3.14159265358979323846
#define VX_MAX 0.35
#define POSITION_KP 1.0
#define YAW_KP 1.5
#define YAW_RATE_MAX 0.7
#define POSITION_TOL 0.03
#define YAW_TOL (2.0 * PI / 180.0)
#define SPEED_TOL 0.12
#define YAW_RATE_TOL 0.10
#define VZ_TOL 0.15
#define ALT_TOL 0.05
#define STOP_WINDOW 0.5
#define ACTION_TIMEOUT 25.0

typedef enum { CMD_IDLE, CMD_TAKEOFF, CMD_MOVE, CMD_LAND } command_t;
static double clip(double v,double l){return v>l?l:(v<-l?-l:v);}static void clip_vector(double*x,double*y,double l){double m=hypot(*x,*y);if(m>l&&m>0){double s=l/m;*x*=s;*y*=s;}}static double motor(double v){return v<0?0:(v>600?600:v);}static double wrap(double a){while(a>PI)a-=2*PI;while(a<=-PI)a+=2*PI;return a;}
static void stop_motors(WbDeviceTag a,WbDeviceTag b,WbDeviceTag c,WbDeviceTag d){wb_motor_set_velocity(a,0);wb_motor_set_velocity(b,0);wb_motor_set_velocity(c,0);wb_motor_set_velocity(d,0);}static void json_vec(FILE*f,const double*v){fprintf(f,"[%.9f,%.9f,%.9f]",v[0],v[1],v[2]);}
static void trace_line(const char*root,const char*op,const char*direction,double value,const double*before,const double*after,double range_m,int stop){char p[4096];snprintf(p,sizeof(p),"%s/ci-artifacts/b4-controller-trace.jsonl",root);FILE*f=fopen(p,"a");if(!f)return;fprintf(f,"{\"op\":\"%s\"",op);if(direction&&direction[0])fprintf(f,",\"direction\":\"%s\"",direction);if(strcmp(op,"range")==0)fprintf(f,",\"value_m\":%.9f",range_m);if(strcmp(op,"takeoff")==0)fprintf(f,",\"height_m\":%.9f",value);if(strcmp(op,"move")==0)fprintf(f,",\"distance_m\":%.9f",value);if(before){fprintf(f,",\"before\":");json_vec(f,before);}if(after){fprintf(f,",\"after\":");json_vec(f,after);}if(stop)fprintf(f,",\"stop\":true");fprintf(f,"}\n");fflush(f);fclose(f);}
static void response(const char*root,int id,int ok,const char*error,const char*op,const char*direction,double value,const double*before,const double*after,double range_m,int stop){char path[4096],tmp[4096];snprintf(path,sizeof(path),"%s/ci-artifacts/b4-response-%d.json",root,id);snprintf(tmp,sizeof(tmp),"%s.tmp",path);FILE*f=fopen(tmp,"w");if(!f)return;fprintf(f,"{\"ok\":%s",ok?"true":"false");if(!ok)fprintf(f,",\"error\":\"%s\"",error?error:"controller failure");if(ok&&strcmp(op,"range")==0)fprintf(f,",\"value_m\":%.9f,\"source\":\"Webots range_front dynamic\"",range_m);if(ok&&before){fprintf(f,",\"before\":");json_vec(f,before);}if(ok&&after){fprintf(f,",\"after\":");json_vec(f,after);}if(ok&&stop)fprintf(f,",\"stop\":true");fprintf(f,"}\n");fflush(f);fclose(f);rename(tmp,path);if(ok)trace_line(root,op,direction,value,before,after,range_m,stop);}
static int read_new_command(const char*root,int last_id,int*id,char*op,char*direction,double*value){char path[4096],line[512];snprintf(path,sizeof(path),"%s/ci-artifacts/b4-command.txt",root);FILE*f=fopen(path,"r");if(!f)return 0;if(!fgets(line,sizeof(line),f)){fclose(f);return 0;}fclose(f);int parsed=sscanf(line,"id=%d op=%31s direction=%31s value=%lf",id,op,direction,value);return parsed>=4&&*id>last_id;}

int main(void){wb_robot_init();const char*root=wb_robot_get_project_path();const int step=(int)wb_robot_get_basic_time_step();WbDeviceTag m1=wb_robot_get_device("m1_motor"),m2=wb_robot_get_device("m2_motor"),m3=wb_robot_get_device("m3_motor"),m4=wb_robot_get_device("m4_motor"),gps=wb_robot_get_device("gps"),imu=wb_robot_get_device("inertial_unit"),gyro=wb_robot_get_device("gyro"),range_front=wb_robot_get_device("range_front");wb_motor_set_position(m1,INFINITY);wb_motor_set_position(m2,INFINITY);wb_motor_set_position(m3,INFINITY);wb_motor_set_position(m4,INFINITY);wb_motor_set_velocity(m1,-1);wb_motor_set_velocity(m2,1);wb_motor_set_velocity(m3,-1);wb_motor_set_velocity(m4,1);wb_gps_enable(gps,step);wb_inertial_unit_enable(imu,step);wb_gyro_enable(gyro,step);wb_distance_sensor_enable(range_front,step);while(wb_robot_step(step)!=-1&&wb_robot_get_time()<2.0){}
const double*p=wb_gps_get_values(gps),*r=wb_inertial_unit_get_roll_pitch_yaw(imu);double origin_z=p[2],target_x=p[0],target_y=p[1],target_z=p[2],target_yaw=r[2],px=p[0],py=p[1],pz=p[2],pt=wb_robot_get_time();int airborne=0,last_id=0,active_id=0;command_t cmd=CMD_IDLE;double stable=-1,action_start=0,value=0;char active_op[32]="",direction[32]="";double before[3]={p[0],p[1],p[2]};gains_pid_t g={0};g.kp_att_y=1;g.kd_att_y=.5;g.kp_att_rp=.5;g.kd_att_rp=.1;g.kp_vel_xy=2;g.kd_vel_xy=.5;g.kp_z=10;g.ki_z=5;g.kd_z=5;init_pid_attitude_fixed_height_controller();actual_state_t a={0};desired_state_t d={0};motor_power_t power={0};char ready[4096];snprintf(ready,sizeof(ready),"%s/ci-artifacts/b4-ready.txt",root);FILE*rf=fopen(ready,"w");if(rf){fprintf(rf,"WEBEEBLOCKS_B4_DYNAMIC_READY\n");fclose(rf);}printf("WEBEEBLOCKS_B4_DYNAMIC_READY\n");fflush(stdout);
while(wb_robot_step(step)!=-1){double now=wb_robot_get_time(),dt=now-pt;if(dt<=0)continue;p=wb_gps_get_values(gps);r=wb_inertial_unit_get_roll_pitch_yaw(imu);const double*gv=wb_gyro_get_values(gyro);double x=p[0],y=p[1],z=p[2],yaw=r[2],vxg=(x-px)/dt,vyg=(y-py)/dt,vz=(z-pz)/dt,cy=cos(yaw),sy=sin(yaw);a.roll=r[0];a.pitch=r[1];a.yaw_rate=gv[2];a.altitude=z;a.vx=vxg*cy+vyg*sy;a.vy=-vxg*sy+vyg*cy;d.roll=0;d.pitch=0;d.vx=0;d.vy=0;d.yaw_rate=0;d.altitude=airborne?target_z:origin_z;
if(cmd==CMD_IDLE){int id;char op[32]={0},dir[32]={0};double val=0;if(read_new_command(root,last_id,&id,op,dir,&val)){last_id=id;if(strcmp(op,"range")==0){if(strcmp(dir,"front")!=0)response(root,id,0,"CAPABILITY_UNAVAILABLE","range",dir,val,NULL,NULL,0,0);else{double m=wb_distance_sensor_get_value(range_front)/1000.0;if(!isfinite(m)||m<0||m>2.001)response(root,id,0,"INVALID_RANGE_SAMPLE","range",dir,val,NULL,NULL,m,0);else response(root,id,1,NULL,"range",dir,val,NULL,NULL,m,0);}}else if(strcmp(op,"takeoff")==0){if(airborne||!isfinite(val)||val<.2||val>1.5)response(root,id,0,"INVALID_TAKEOFF","takeoff","",val,NULL,NULL,0,0);else{active_id=id;cmd=CMD_TAKEOFF;strcpy(active_op,"takeoff");direction[0]=0;value=val;before[0]=x;before[1]=y;before[2]=z;target_x=x;target_y=y;target_yaw=yaw;target_z=origin_z+val;stable=-1;action_start=now;}}else if(strcmp(op,"move")==0){if(!airborne||!isfinite(val)||val<.1||val>2.0||(strcmp(dir,"forward")&&strcmp(dir,"left")))response(root,id,0,"INVALID_MOVE","move",dir,val,NULL,NULL,0,0);else{active_id=id;cmd=CMD_MOVE;strcpy(active_op,"move");strcpy(direction,dir);value=val;before[0]=x;before[1]=y;before[2]=z;target_yaw=yaw;if(!strcmp(dir,"forward")){target_x=x+cos(yaw)*val;target_y=y+sin(yaw)*val;}else{target_x=x-sin(yaw)*val;target_y=y+cos(yaw)*val;}stable=-1;action_start=now;}}else if(strcmp(op,"land")==0){if(!airborne)response(root,id,0,"INVALID_LAND","land","",0,NULL,NULL,0,0);else{active_id=id;cmd=CMD_LAND;strcpy(active_op,"land");direction[0]=0;value=0;before[0]=x;before[1]=y;before[2]=z;target_z=origin_z;stable=-1;action_start=now;}}else response(root,id,0,"UNKNOWN_OP",op,dir,val,NULL,NULL,0,0);}}
if(cmd!=CMD_IDLE&&(fabs(a.roll)>1.2||fabs(a.pitch)>1.2||now-action_start>ACTION_TIMEOUT)){response(root,active_id,0,"UNSAFE_OR_TIMEOUT",active_op,direction,value,NULL,NULL,0,0);stop_motors(m1,m2,m3,m4);break;}
if(cmd==CMD_TAKEOFF){d.altitude=target_z;if(fabs(z-target_z)<ALT_TOL&&fabs(vz)<VZ_TOL&&hypot(a.vx,a.vy)<SPEED_TOL&&fabs(a.yaw_rate)<YAW_RATE_TOL){if(stable<0)stable=now;if(now-stable>=STOP_WINDOW){double after[3]={x,y,z};airborne=1;response(root,active_id,1,NULL,"takeoff","",value,before,after,0,1);cmd=CMD_IDLE;stable=-1;}}else stable=-1;}else if(cmd==CMD_MOVE){double ex=target_x-x,ey=target_y-y,bx=ex*cy+ey*sy,by=-ex*sy+ey*cy;d.vx=POSITION_KP*bx;d.vy=POSITION_KP*by;clip_vector(&d.vx,&d.vy,VX_MAX);d.yaw_rate=clip(YAW_KP*wrap(target_yaw-yaw),YAW_RATE_MAX);d.altitude=target_z;if(hypot(ex,ey)<=POSITION_TOL&&fabs(wrap(target_yaw-yaw))<=YAW_TOL&&hypot(a.vx,a.vy)<SPEED_TOL&&fabs(a.yaw_rate)<YAW_RATE_TOL&&fabs(vz)<VZ_TOL&&fabs(z-target_z)<ALT_TOL){if(stable<0)stable=now;if(now-stable>=STOP_WINDOW){double after[3]={x,y,z};response(root,active_id,1,NULL,"move",direction,value,before,after,0,1);cmd=CMD_IDLE;stable=-1;}}else stable=-1;}else if(cmd==CMD_LAND){d.altitude=origin_z;if(z<=origin_z+ALT_TOL&&fabs(vz)<VZ_TOL){if(stable<0)stable=now;if(now-stable>=STOP_WINDOW){double after[3]={x,y,z};stop_motors(m1,m2,m3,m4);airborne=0;response(root,active_id,1,NULL,"land","",0,before,after,0,1);cmd=CMD_IDLE;stable=-1;continue;}}else stable=-1;}else if(airborne){double ex=target_x-x,ey=target_y-y,bx=ex*cy+ey*sy,by=-ex*sy+ey*cy;d.vx=POSITION_KP*bx;d.vy=POSITION_KP*by;clip_vector(&d.vx,&d.vy,VX_MAX);d.yaw_rate=clip(YAW_KP*wrap(target_yaw-yaw),YAW_RATE_MAX);d.altitude=target_z;}
if(airborne||cmd!=CMD_IDLE){pid_velocity_fixed_height_controller(a,&d,g,dt,&power);wb_motor_set_velocity(m1,-motor(power.m1));wb_motor_set_velocity(m2,motor(power.m2));wb_motor_set_velocity(m3,-motor(power.m3));wb_motor_set_velocity(m4,motor(power.m4));}else stop_motors(m1,m2,m3,m4);pt=now;px=x;py=y;pz=z;}
stop_motors(m1,m2,m3,m4);wb_robot_cleanup();return 0;}
