#!/usr/bin/env python3
"""Execute the vendored Blockly 2020 runtime against the six historical XML fixtures.

The static gate proves that the fixture bytes, registrations and loaded scripts
remain intact. This browser oracle goes further: it deserializes each preserved
XML program with the real vendored Blockly runtime, regenerates Python, compiles
it, and requires the generated bytes to match the historical reference digests.
"""

from __future__ import annotations

import hashlib
import html
import json
import re
import shutil
import subprocess
import sys
import tempfile
from html.parser import HTMLParser
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
ROBOT_WINDOW_DIR = ROOT / "plugins" / "robot_windows" / "blockly"
HTML_PATH = ROBOT_WINDOW_DIR / "blockly.html"
PROGRAM_DIR = ROOT / "controllers" / "Blockly_Programs"

EXPECTED_PYTHON_SHA256 = {
    "BoxWithDistSensor.xml": "e1624142889a335b5fce174ac2b95253f471252cc486155a1d9aa08cca677345",
    "BoxWithEncoders.xml": "82428f9bbec590dcca8e4b4362c7ddafbb428632578700e9f63273f3766e5a01",
    "BoxWithGyroGPS.xml": "7c7caa50b8e8968bff5b531b98f4223eac73bd82947ca6cea4fbc00455ea40cf",
    "BoxWithLightSensor.xml": "a1951e9d2a530f99475aaa7cc88e1369439431c7c63a847ca9971f94a9fa95e7",
    "myFile.xml": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "sensorProbing.xml": "b298bcbae88a2a141159ba17cb2e423ee8a691d440ab68f747d285d04f8a1050",
}
PROGRAMS = tuple(EXPECTED_PYTHON_SHA256)
RESULT_RE = re.compile(r'<pre id="oracle-result">(.*?)</pre>', re.DOTALL)


class ScriptParser(HTMLParser):
    def __init__(self) -> None:
        super().__init__()
        self.sources: list[str] = []

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        if tag.lower() != "script":
            return
        src = dict(attrs).get("src")
        if src and src.startswith("google-blockly-31ee4ea/"):
            self.sources.append(src)


def chrome_executable() -> str:
    for candidate in ("google-chrome", "google-chrome-stable", "chromium", "chromium-browser"):
        path = shutil.which(candidate)
        if path:
            return path
    raise RuntimeError("no Chrome/Chromium executable found on the CI runner")


def build_harness() -> str:
    parser = ScriptParser()
    parser.feed(HTML_PATH.read_text(encoding="utf-8"))
    if not parser.sources:
        raise RuntimeError("blockly.html did not expose any vendored Blockly scripts")

    script_tags = "\n".join(f'<script src="{html.escape(src)}"></script>' for src in parser.sources)
    programs = {name: (PROGRAM_DIR / name).read_text(encoding="utf-8") for name in PROGRAMS}
    payload = json.dumps(programs)

    return f"""<!doctype html>
<html>
<head><meta charset=\"utf-8\">{script_tags}</head>
<body><pre id=\"oracle-result\">NOT_RUN</pre>
<script>
(function() {{
  const programs = {payload};
  const result = {{ok: true, programs: {{}}}};
  try {{
    for (const [name, xmlText] of Object.entries(programs)) {{
      const workspace = new Blockly.Workspace();
      const xml = Blockly.Xml.textToDom(xmlText);
      Blockly.Xml.domToWorkspace(xml, workspace);
      const code = Blockly.Python.workspaceToCode(workspace);
      result.programs[name] = {{code: code, topBlocks: workspace.getTopBlocks(false).length}};
      workspace.dispose();
    }}
  }} catch (error) {{
    result.ok = false;
    result.error = String(error && error.stack ? error.stack : error);
  }}
  document.getElementById('oracle-result').textContent = JSON.stringify(result);
}})();
</script></body></html>"""


def parse_browser_output(stdout: str) -> dict[str, object]:
    match = RESULT_RE.search(stdout)
    if not match:
        raise RuntimeError("headless browser did not emit oracle-result")
    raw = html.unescape(match.group(1))
    if raw == "NOT_RUN":
        raise RuntimeError("Blockly harness JavaScript did not run")
    return json.loads(raw)


def run_browser(harness_path: Path) -> dict[str, object]:
    chrome = chrome_executable()
    command = [
        chrome,
        "--headless=new",
        "--no-sandbox",
        "--disable-gpu",
        "--disable-dev-shm-usage",
        "--disable-background-networking",
        "--allow-file-access-from-files",
        "--virtual-time-budget=5000",
        "--dump-dom",
        harness_path.as_uri(),
    ]
    process = subprocess.Popen(
        command,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    timed_out = False
    try:
        stdout, stderr = process.communicate(timeout=30)
    except subprocess.TimeoutExpired:
        # Some hosted Chrome builds can finish --dump-dom yet linger during
        # browser shutdown. Kill the browser, collect its already-produced DOM,
        # and accept the run only if the oracle payload is actually present.
        timed_out = True
        process.kill()
        stdout, stderr = process.communicate()

    try:
        parsed = parse_browser_output(stdout)
    except RuntimeError as exc:
        if timed_out:
            raise RuntimeError(
                f"headless browser timed out before emitting oracle-result: {stderr.strip()}"
            ) from exc
        if process.returncode:
            raise RuntimeError(
                f"headless browser exited with {process.returncode}: {stderr.strip()}"
            ) from exc
        raise

    if not timed_out and process.returncode:
        raise RuntimeError(
            f"headless browser exited with {process.returncode}: {stderr.strip()}"
        )
    if timed_out:
        print(
            "WARN: headless browser required forced shutdown after emitting oracle-result; accepting the verified DOM payload.",
            file=sys.stderr,
        )
    return parsed


def main() -> int:
    harness = build_harness()
    with tempfile.NamedTemporaryFile(
        mode="w", suffix=".html", dir=ROBOT_WINDOW_DIR, encoding="utf-8", delete=False
    ) as handle:
        handle.write(harness)
        harness_path = Path(handle.name)

    try:
        result = run_browser(harness_path)
    finally:
        harness_path.unlink(missing_ok=True)

    if not result.get("ok"):
        print(f"FAIL: Blockly browser execution failed: {result.get('error')}", file=sys.stderr)
        return 1

    generated = result.get("programs")
    if not isinstance(generated, dict) or set(generated) != set(PROGRAMS):
        print("FAIL: browser result does not contain exactly the six historical programs", file=sys.stderr)
        return 1

    failures: list[str] = []
    nonempty = 0
    print("Historical Blockly browser oracle")
    for name in PROGRAMS:
        entry = generated[name]
        if not isinstance(entry, dict):
            failures.append(f"malformed browser result for {name}")
            continue
        code = entry.get("code")
        if not isinstance(code, str):
            failures.append(f"generated code is not text for {name}")
            continue

        if code.strip():
            nonempty += 1
            try:
                compile(code, f"<Blockly:{name}>", "exec")
            except SyntaxError as exc:
                failures.append(f"generated Python is invalid for {name}: {exc}")

        code_bytes = code.encode("utf-8")
        digest = hashlib.sha256(code_bytes).hexdigest()
        expected_digest = EXPECTED_PYTHON_SHA256[name]
        print(
            f"  {name}: topBlocks={entry.get('topBlocks')}, "
            f"pythonBytes={len(code_bytes)}, sha256={digest}"
        )
        if digest != expected_digest:
            failures.append(
                f"generated Python drift for {name}: sha256={digest}, expected={expected_digest}"
            )

    if nonempty != 5:
        failures.append(f"expected five non-empty generated programs, got {nonempty}")

    if failures:
        print("\nFAIL", file=sys.stderr)
        for failure in failures:
            print(f"- {failure}", file=sys.stderr)
        return 1

    print(
        "PASS: Blockly 2020 reproduced the exact historical Python byte output for all six preserved XML fixtures; the five non-empty outputs also compile."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
