(function(root, factory) {
  if (typeof module === 'object' && module.exports)
    module.exports = factory();
  else
    root.WebeeBlocksActivities = factory();
})(typeof self !== 'undefined' ? self : this, function() {
  'use strict';
  var BLOCK_CATALOG = Object.freeze({webeeblocks_takeoff:{category:'flight'},webeeblocks_forward:{category:'flight'},webeeblocks_turn:{category:'flight'},webeeblocks_land:{category:'flight'},webeeblocks_v2_takeoff:{category:'flight'},webeeblocks_v2_land:{category:'flight'},webeeblocks_v2_move:{category:'flight'},webeeblocks_v2_vertical:{category:'flight'},webeeblocks_v2_turn:{category:'flight'},webeeblocks_v2_wait:{category:'control'},webeeblocks_v2_speed:{category:'flight'},webeeblocks_v2_range:{category:'sensor'},controls_if:{category:'control'},controls_repeat_ext:{category:'control'},logic_compare:{category:'operator'},logic_operation:{category:'operator'},math_number:{category:'operator'}});
  var DOCUMENT = Object.freeze({version:1,activities:[
    {id:'progression-sequence-v1',world:'worlds/crazyflie_runtime_obstacle.wbt',brief:{visible:true,title:'1 — Décoller, avancer, atterrir',goal:'Construis une séquence simple : décolle, avance, puis atterris.'},toolbox:['webeeblocks_v2_takeoff','webeeblocks_v2_move','webeeblocks_v2_land'],parameterBounds:{webeeblocks_v2_takeoff:{HEIGHT:{min:0.5,max:1.0,step:0.1}},webeeblocks_v2_move:{DISTANCE:{min:0.1,max:1.2,step:0.1}}},fieldOptions:{webeeblocks_v2_move:{DIRECTION:['forward']}},hardware:['crazyflie-2.1','flow-deck-v2'],timer:{enabled:false},evaluation:{type:'training-objective'},runtime:{mode:'ast-v1',allowedStatementKinds:['takeoff','move','land'],rangeDirections:[],moveDirections:['forward'],verticalDirections:[],astBounds:{'takeoff.height_m':{min:0.5,max:1.0},'move.distance_m':{min:0.1,max:1.2}}}},
    {id:'progression-repeat-v1',world:'worlds/crazyflie_runtime_obstacle.wbt',brief:{visible:true,title:'2 — Répéter un déplacement',goal:'Réutilise la séquence précédente et emploie une répétition pour construire un trajet régulier.'},toolbox:['webeeblocks_v2_takeoff','webeeblocks_v2_move','controls_repeat_ext','math_number','webeeblocks_v2_land'],parameterBounds:{webeeblocks_v2_takeoff:{HEIGHT:{min:0.5,max:1.0,step:0.1}},webeeblocks_v2_move:{DISTANCE:{min:0.1,max:1.2,step:0.1}},math_number:{NUM:{min:1,max:10,step:1}}},fieldOptions:{webeeblocks_v2_move:{DIRECTION:['forward']}},hardware:['crazyflie-2.1','flow-deck-v2'],timer:{enabled:false},evaluation:{type:'training-objective'},runtime:{mode:'ast-v1',allowedStatementKinds:['takeoff','move','repeat','land'],rangeDirections:[],moveDirections:['forward'],verticalDirections:[],astBounds:{'takeoff.height_m':{min:0.5,max:1.0},'move.distance_m':{min:0.1,max:1.2},'repeat.count':{min:1,max:10}}}},
    {id:'progression-reactive-v1',world:'worlds/crazyflie_runtime_obstacle.wbt',brief:{visible:true,title:'3 — Mesurer puis décider',goal:'Réutilise mouvements et répétition, mesure la distance devant le drone et décide quand avancer ou aller à gauche.'},toolbox:['webeeblocks_v2_takeoff','webeeblocks_v2_move','controls_repeat_ext','math_number','webeeblocks_v2_range','controls_if','logic_compare','webeeblocks_v2_land'],parameterBounds:{webeeblocks_v2_takeoff:{HEIGHT:{min:0.5,max:1.0,step:0.1}},webeeblocks_v2_move:{DISTANCE:{min:0.1,max:1.2,step:0.1}},math_number:{NUM:{min:1,max:10,step:1}}},fieldOptions:{webeeblocks_v2_move:{DIRECTION:['forward','left']},webeeblocks_v2_range:{DIRECTION:['front']}},hardware:['crazyflie-2.1','flow-deck-v2','multi-ranger-deck'],timer:{enabled:false},evaluation:{type:'training-objective'},runtime:{mode:'ast-v1',allowedStatementKinds:['takeoff','move','repeat','if','land'],rangeDirections:['front'],moveDirections:['forward','left'],verticalDirections:[],astBounds:{'takeoff.height_m':{min:0.5,max:1.0},'move.distance_m':{min:0.1,max:1.2},'repeat.count':{min:1,max:10}}}},
    {id:'progression-combined-decisions-v1',world:'worlds/crazyflie_runtime_obstacle.wbt',brief:{visible:true,title:'4 — Combiner des décisions',goal:'Réutilise les acquis précédents, mesure devant, à gauche et à droite, puis compose et imbrique plusieurs décisions.'},toolbox:['webeeblocks_v2_takeoff','webeeblocks_v2_move','controls_repeat_ext','math_number','webeeblocks_v2_range','controls_if','logic_compare','logic_operation','webeeblocks_v2_land'],parameterBounds:{webeeblocks_v2_takeoff:{HEIGHT:{min:0.5,max:1.0,step:0.1}},webeeblocks_v2_move:{DISTANCE:{min:0.1,max:1.2,step:0.1}},math_number:{NUM:{min:1,max:10,step:1}}},fieldOptions:{webeeblocks_v2_move:{DIRECTION:['forward','left']},webeeblocks_v2_range:{DIRECTION:['front','left','right']}},hardware:['crazyflie-2.1','flow-deck-v2','multi-ranger-deck'],timer:{enabled:false},evaluation:{type:'training-objective'},runtime:{mode:'ast-v1',allowedStatementKinds:['takeoff','move','repeat','if','land'],rangeDirections:['front','left','right'],moveDirections:['forward','left'],verticalDirections:[],astBounds:{'takeoff.height_m':{min:0.5,max:1.0},'move.distance_m':{min:0.1,max:1.2},'repeat.count':{min:1,max:10}}}},
    {id:'obstacle-time-trial-v1',world:'worlds/crazyflie_runtime_obstacle.wbt',brief:{visible:true,title:'Défi Crazyflie — contre-la-montre',goal:'Franchis les deux portes dans l’ordre, évite l’obstacle puis atterris. Quand ton parcours réussit, améliore ton temps.'},toolbox:['webeeblocks_takeoff','webeeblocks_forward','webeeblocks_turn','webeeblocks_land'],parameterBounds:{webeeblocks_forward:{DISTANCE:{min:0.1,max:2.0,step:0.1}},webeeblocks_turn:{ANGLE:{min:-90,max:135,step:1}}},hardware:['crazyflie-2.1','flow-deck-v2'],timer:{enabled:true},evaluation:{type:'ordered-gates-no-collision'},runtime:{mode:'mission-v1',allowedStatementKinds:['takeoff','move','turn','land'],rangeDirections:[],moveDirections:['forward'],verticalDirections:[],astBounds:{'takeoff.height_m':{min:1.0,max:1.0},'move.distance_m':{min:0.1,max:2.0},'turn.angle_deg_abs':{min:1,max:135}}}},
    {id:'reactive-obstacle-v2',world:'worlds/crazyflie_runtime_obstacle.wbt',brief:{visible:true,title:'Crazyflie — comportement réactif',goal:'Observe les distances pendant le vol et décide du déplacement à exécuter.'},toolbox:['webeeblocks_v2_takeoff','webeeblocks_v2_move','webeeblocks_v2_vertical','webeeblocks_v2_turn','webeeblocks_v2_wait','webeeblocks_v2_speed','webeeblocks_v2_range','controls_if','controls_repeat_ext','logic_compare','logic_operation','math_number','webeeblocks_v2_land'],parameterBounds:{webeeblocks_v2_takeoff:{HEIGHT:{min:0.2,max:1.5,step:0.1}},webeeblocks_v2_move:{DISTANCE:{min:0.1,max:2.0,step:0.1}},webeeblocks_v2_vertical:{DISTANCE:{min:0.1,max:0.8,step:0.1}},webeeblocks_v2_turn:{ANGLE:{min:1,max:179,step:1}},webeeblocks_v2_wait:{SECONDS:{min:0.1,max:5.0,step:0.1}},webeeblocks_v2_speed:{SPEED:{min:0.1,max:0.6,step:0.1}}},hardware:['crazyflie-2.1','flow-deck-v2','multi-ranger-deck'],timer:{enabled:false},evaluation:{type:'reactive-runtime'},runtime:{mode:'ast-v1',allowedStatementKinds:['takeoff','move','vertical','turn','wait','set_speed','if','repeat','land'],rangeDirections:['front','back','left','right','up'],moveDirections:['forward','back','left','right'],verticalDirections:['up','down'],astBounds:{'takeoff.height_m':{min:0.2,max:1.5},'move.distance_m':{min:0.1,max:2.0},'vertical.distance_m':{min:0.1,max:0.8},'turn.angle_deg_abs':{min:1,max:179},'wait.seconds':{min:0.1,max:5.0},'set_speed.speed_m_s':{min:0.1,max:0.6},'repeat.count':{min:1,max:20}}}}
  ]});
  function getProfile(id) { var matches = DOCUMENT.activities.filter(function(profile) { return profile.id === id; }); if (matches.length !== 1) throw new Error('unknown activity: ' + id); return JSON.parse(JSON.stringify(matches[0])); }
  return {BLOCK_CATALOG:BLOCK_CATALOG,DOCUMENT:DOCUMENT,getProfile:getProfile};
});
